language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - cd /home/travis/build/makism/dyconnmap/tests/
  - nosetests --cover-tests --with-coverage --cover-package=dyconnmap

after_success:
  - coveralls
  - coverage xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml  final
  - codecov
